#!/bin/bash
if [ "$#" -lt 3 ]; then
    echo 'Usage: aryana_bs <reference genome> <CpG islands file> <input sam file> <output of accuracy> <folder of output samfiles>'
    exit
fi

PostAlignment() {

for (( i = 1; i<= 10; i+=2 ))
do
for (( j = 1; j <= 10; j+=2 ))
do
high=$(( $i * $j))
echo "Finding the best alignment for each read..."
"$DIR/align_bs" -x "$1" -c "$2" -s "$3_out/temp.sam" -p 1 "$high" "$i" -o "$5/1_"$high"_$i.sam" -h "a.sam"
"$DIR/accuracy" "$5/1_"$high"_$i.sam" >> "$4"
done
done
    echo "Finished."
}

DIR=$(dirname $(readlink -f $0));
mkdir "$5"
if [ "$#" -gt 4 ]; then
    declare "${*:5}"
fi

PostAlignment "$@" &
exit

